### ISSUE TITLE
Modularise tool wrapper architecture

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/educationplatform#4]
- [x] Separate tool wrapper for EMFatic, Flexmi, Epsilon, OCL
- [x] Extension of tool api with function for translating panel contents into xmi.
- [x] #17
- [x] Document updated architecture and implementation protocols.

**Comment by barnettwilliam** [comment]
Added  documentation on tool wrapper architecture and protocols to the wiki under Adding a Tool - Tool Service:  https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/932c0c528c9426bc86474c399d0c09d7eb7830c9

**Comment by barnettwilliam** [comment]
@szschaler please review the documentation and close

**Comment by szschaler** [comment]
Hi @barnettwilliam,

Have looked at this (btw, is there a way to manage these through something like a PR?). Overall look quite good. A few small comments:

- [ ] [Tool Service](https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/932c0c528c9426bc86474c399d0c09d7eb7830c9#tool-service): This would benefit from a small example. In particular:
  - [ ] I found the [_file_] parameter notation a bit confusing: if I understand correctly, these are actually unique keys for each file parameter, but that doesn't come out very clearly from the text.
  - [ ] Do the [_file_] parameters follow a particular encoding?
- [ ] [File parameter](https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/932c0c528c9426bc86474c399d0c09d7eb7830c9#file): should this reference briefly the use of conversion functions, at least to say that tool functions can fix their expectation of file format based on whatever is best for them?
- [ ] [Response Specification](https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/932c0c528c9426bc86474c399d0c09d7eb7830c9#response-specification): should we document that the four options are mutually exclusive (or aren't they)?
- [ ] [Java-based implementation](https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/932c0c528c9426bc86474c399d0c09d7eb7830c9#java-based-implementation): which of these classes and interfaces are provided by us and which does the tool provider have to implement? Is it possible to provide this as a template repository to get people started more easily?
- [ ] [Function](https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/932c0c528c9426bc86474c399d0c09d7eb7830c9#function): This needs some explanatory text: what is a function and how do the parameters here map on the constituent parts of a function?
- [ ] [Parameter](https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/932c0c528c9426bc86474c399d0c09d7eb7830c9#parameter) ditto
- [ ] [Panel](https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/932c0c528c9426bc86474c399d0c09d7eb7830c9#paneldef): ditto. Moreover, we haven't introduced what a panel is or what the different types of panel do.
- [ ] [Button](https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/932c0c528c9426bc86474c399d0c09d7eb7830c9#button): need to explain what a button is conceptually -- for example, that it corresponds to one of the buttons that will show in the panel.

Otherwise, looks very good!

**Comment by barnettwilliam** [comment]
> btw, is there a way to manage these through something like a PR?

There is no direct way to do this through the github ui. However, the wiki is a git repo so
-  it could be cloned into it's own private documentation repo where the pull requests are available and then as a github action be merged into the public wiki.   
- or  it may also be possible to use git subtree to add the wiki to a documentation subfolder of the mdenet/educationplatform repo and use pull requests there manage the changes. Then, as an action on merging to main, subtree push the documentation to the the wiki to keep it up to date.

**Comment by barnettwilliam** [comment]
> [Response Specification](https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/932c0c528c9426bc86474c399d0c09d7eb7830c9#response-specification): should we document that the four options are mutually exclusive (or aren't they)? 

They are currently mutually exclusive but some original playground behaviour has been unintentionally lost - the display of tool  terminal output. 

So at the moment responses are handled mutually exclusively but there should be an exception so that any tool terminal output is displayed on an available console panel. 

> Is it possible to provide this as a template repository to get people started more easily? 

Yes

- [ ] Create template repository.

**Comment by szschaler** [comment]
Re the response specification, let's do the following: 

- [ ] document that it's currently mutually exclusive
- [ ] add an issue to fix this and allow multiple responses from a tool function

**Comment by barnettwilliam** [comment]
Added note to documentation https://github.com/mdenet/educationplatform/wiki/Adding-a-Tool/72da2cd9d4dc9c2e9284e0490d43c045e1c13cf6  


Issue raised #80
