### ISSUE TITLE
Tool configuration should contain information for discoverability

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/educationplatform#77]
A review comment from the MODELS paper suggested the tool configuration should contain extra information for discoverability when there are multiple tool providers e.g. version, date, author, contact information.

**Comment by jgsuess** [comment]
Hi!
Sorry to butt in, but it seems you are on a road to reinvent the wheel. Eclipse went down this path with Eclipse 1.0, only to reset and replace infrastructure with OSGi. Please have a serious look at [Eclipse RAP](https://eclipse.dev/rap/). It will allow you to dual use substantial amounts of infrastructure. If you do not like this, and want to focus on JS, please consider [EMF Cloud](https://eclipse.dev/emfcloud/). You will not have the resources to sustain the growth and cannot be an expert in all the facilities.

As for the feature request, in Eclipse P2 and marketplace offer this function, which will also be available in RAP.

**Comment by szschaler** [comment]
@jgsuess, you make a valid point. We did look at RAP, but initially didn't go down that route as I'm not sure we want to stay in the EMF world only in the long term. emf.cloud is similar, I guess. 

I was interested in seeing that things like GLSP have broadened their backends quite significantly to cover non-EMF technologies, too. I'm beginning to think that we may need to look at this in more detail at some point soon. A similar consideration holds for [LIonWeb](https://tomassetti.me/lionweb-building-great-language-engineering-applications/), which perhaps is the most promising thing here. I'm hoping to learn more about this at the [education platform workshop at MODELS](https://modellingtoolsforteaching.github.io/).

At this point, we're trying to build a basic proof of concept for the education platform and learn about architectural requirements so that we can get a better basis for assessing these different alternatives for best fit. The purpose of this particular issue here is to keep track of suggestions, not to say that we will definitely focus on this.

**Comment by jgsuess** [comment]
With regard to GLSP I recommend building on [ELK}(https://eclipse.dev/elk/). ELK can back GLSP and is multi-language and multi-target. I see great promise in ELK.
